# Generated by Django 4.1.4 on 2022-12-16 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=7, message='Меньше 7')])),
            ],
        ),
        migrations.CreateModel(
            name='folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Меньше 5')])),
                ('department', models.CharField(choices=[('KO', 'Коммерческий'), ('FI', 'Финансовый'), ('MA', 'Маркетинговый')], default=None, max_length=2)),
                ('files', models.ManyToManyField(to='webapp.file')),
            ],
        ),
    ]
