# Generated by Django 4.1.4 on 2022-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='department_user',
            field=models.CharField(choices=[('KO', 'Коммерческий'), ('FI', 'Финансовый'), ('MA', 'Маркетинговый')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
