# Generated by Django 4.1.4 on 2022-12-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='doc/'),
        ),
        migrations.RemoveField(
            model_name='folder',
            name='files',
        ),
        migrations.AddField(
            model_name='folder',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.file'),
        ),
    ]
